### PR TITLE
Add parameter validation and provide additional information to response header about the error

### PR DESCRIPTION
**Pull request by jerico**
This PR adds validation to parameters passed to Tachyon. If the parameter is not valid, it will fall back to default. An additional response header is added `X-Tachyon-Errors` that will specify which parameter is not valid.

### CODE REVIEW

**Review by roborourke — APPROVED** [review]
This looks good to me, thanks @jerico

**Comment by roborourke** [comment]
Can you check on the travis builds and why those are failing before merging @jerico ?

**Comment by jerico** [comment]
@roborourke I missed to notice that it failed. Will check before merging. Thank you!

**Comment by jerico** [comment]
The error was about a PNG file `Website.png` being larger when tachyon processed it

**Comment by jerico** [comment]
```
hdr.jpg-small.jpeg is larger than image in fixtures (43 bytes larger, 100.40608178298234%.)
hdr.jpg-medium.jpeg is larger than image in fixtures (287 bytes larger, 101.19087136929461%.)
hdr.jpg-large.jpeg is larger than image in fixtures (22 bytes larger, 100.02513337826878%.)
briefing-copywriting.jpg-large.jpeg is larger than image in fixtures (58 bytes larger, 100.19847380487971%.)
briefing-copywriting.jpg-webp.webp is larger than image in fixtures (116 bytes larger, 100.74074074074073%.)
icons.png-small.png is larger than image in fixtures (39 bytes larger, 100.98784194528876%.)
icons.png-medium.png is larger than image in fixtures (368 bytes larger, 103.28219764537995%.)
icons.png-large.png is larger than image in fixtures (1212 bytes larger, 104.59578340664342%.)
humans.png-large.png is larger than image in fixtures (817 bytes larger, 100.29216657428432%.)
humans.png-webp.webp is larger than image in fixtures (1188 bytes larger, 100.84052639026461%.)
```

TravisCI is failing because of these. It has been failing even before this PR. I'm looking for a fix.

**Comment by roborourke** [comment]
That's super weird the image file fixtures changed by such small amounts 🤔 Thanks for figuring it out and updating!

**Comment by roborourke** [comment]
I think this can be done as a patch release once confirmed working on our test stack. We'll need to also bump the version of the container used by Local Server too.

**Pull request merged**
