### PR TITLE
Allow passing custom client arguments to S3 client

### PR DESCRIPTION
**Pull request by shadyvb**
Allows modifying S3 client options via environment variables, so implementations can use options like s3BucketEndpoint to customize the client.

ref https://github.com/humanmade/product-dev/issues/1033 and https://github.com/humanmade/altis-local-server/pull/341

### CODE REVIEW

**Comment by shadyvb** [comment]
This isn't using path style rather bucket endpoint, so it doesn't play with the URL at all. Traefik then adds the bucket endpoint as a path prefix. Quite the workaround! but fits all our cases.

I wouldn't know what else we'd need, but it made sense to allow arbitrary options for the future. Why not was my philosophy for this change.

**Review by roborourke — APPROVED** [review]

**Comment by roborourke** [comment]
Minor version bump seems appropriate here

**Comment by shadyvb** [comment]
Released as https://github.com/humanmade/tachyon/releases/tag/v2.6.0

**Comment by roborourke** [comment]
Nice, docker image should be available by now then

**Pull request merged**
