### PR TITLE
Support multiarch builds

### PR DESCRIPTION
**Pull request by roborourke**
- Uses node alpine and server.js instead of lambda env
- Uses Docker meta step for tagging

### CODE REVIEW

**Comment by roborourke** [comment]
There's an ARM & AMD build with the tag `humanmade/tachyon:pr-136` to try out. Local testing works for me but would be good to confirm on an M1 machine.

**Comment by ntwb** [comment]
Thanks @roborourke, initial findings here, if there are any further testing or test cases I can verify let me know, happy to test further

### Logs

When looking at the Docker logs for the M1 container using `humanmade/tachyon:pr-136` I see:

I also see it's using the ARM64 image which is neat, thanks 💯
```
Server running at

=> http://localhost:8080/

CTRL + C to shutdown

(node:9) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

(Use `node --trace-warnings ...` to show where the warning was created)
```

### Testing

Uploading an image `test.png` to the media library I see the following in the Docker container logs:

```log
Tue Aug 17 2021 07:14:37 GMT+0000 (Coordinated Universal Time) /uploads/2021/08/test.png?resize=150%2C150&crop_strategy=smart

Tue Aug 17 2021 07:14:50 GMT+0000 (Coordinated Universal Time) /uploads/2021/08/test.png?fit=60%2C33&zoom=2

Tue Aug 17 2021 07:15:06 GMT+0000 (Coordinated Universal Time) /uploads/2021/08/test.png?fit=814%2C450

Tue Aug 17 2021 07:16:37 GMT+0000 (Coordinated Universal Time) /uploads/2021/08/test.png
```

### Works:
- ✅ I can see the image in the media library e.g. `/wp-admin/post.php?post=123&action=edit`

### Does Not Work:

- ❌ When opening the attachment permalink I should see the image, eg `https://altis.dev/test/`
  - Result 404 Not Found
- ❌ In the attachment metabox, clicking "Copy URL to Clipboard" and opening that link in a new tab I should see the uploaded attachment/image e.g `https://altis.dev/uploads/2021/08/test.png`
  - Result 404 Not Found

### Observations

When right-clicking the image from the media library and selecting "Open image in new tab" the image successfully loads, e.g `https://altis.dev/tachyon/2021/08/test.png`

Noticing here the URL is using `/tachyon` instead of `/uploads` 

This also works, cropped image with /tachyon base `https://altis.dev/tachyon/2021/08/test.png?fit=814%2C450`

**Comment by roborourke** [comment]
The URLs you describe there are for `https://altis.dev` - altis.dev just resolves to 127.0.0.1. I'm a bit confused as to how you got that running tbh, I would expect it to work at `<project>.altis.dev`.

**Comment by ntwb** [comment]
Oops, I anonymized those URLs and removed the project name, they are in fact `project.altis.dev`

Some further testing revealed working in the cloud, and partially locally, though this in fact might be expected because of how Tachyon functions:

Media URLs change based on the view type in the media library, the two views are:
- Media Library List View `/wp-admin/upload.php?mode=list`
  - In list view, the URL base `uploads` is used `subdomain.example.com/uploads/...`
- Gallery View - `/wp-admin/upload.php`
  - In list view, the URL base `tachyon` is used `subdomain.example.com/tachyon/...`

Note: Testing was only performed on the local media library, no testing for the global media library

## Cloud Scenario: Media URLs

Opening the same image in an Altis Demo _Cloud_ Site:
- List - https://example.altis.cloud/wp-admin/post.php?post=713&action=edit
  - URL = `https://example.altis.cloud/uploads/2021/08/photo-1616077147157-bbed557e0907.jpeg`
  - image
  - ✅ URL resolves correctly to an image: https://example.altis.cloud/uploads/2021/08/photo-1616077147157-bbed557e0907.jpeg

- Gallery - https://example.altis.cloud/wp-admin/upload.php?item=713
  - URL = `https://example.altis.cloud/tachyon/2021/08/photo-1616077147157-bbed557e0907.jpeg`
  - image
  - ✅ URL resolves correctly to an image: https://example.altis.cloud/tachyon/2021/08/photo-1616077147157-bbed557e0907.jpeg


## Local Scenario: Media URLs

Opening the same image in an Altis Demo Local Site:

- List - https://example.altis.dev/wp-admin/post.php?post=1204015&action=edit
  - URL = `https://example.altis.dev/uploads/2021/08/contact-us-4x3-644.jpg`
  - image
  - ❌ URL does not resolves correctly to an image: https://example.altis.dev/uploads/2021/08/contact-us-4x3-644.jpg

- Gallery - https://example.altis.dev/wp-admin/upload.php?item=713
  - URL = `https://example.altis.dev/tachyon/2021/08/contact-us-4x3-644.jpg`
  - image
  - ✅ URL resolves correctly to an image: https://example.altis.dev/tachyon/2021/08/contact-us-4x3-644.jpg

## Summary

When opening an attachment in the media library from list view with Altis Local Server the `File URL:` displayed in the metabox uses `/uploads` as the path and once copying that URL to the clipboard and opening it in a new browser tab results in a 404 not found.

image

**Comment by roborourke** [comment]
Seems the takeaway then is that the tachyon container works fine but we might have an issue with the uploads URL mapping on local server which would be a separate problem to solve. Does that sound right to you?

**Comment by roborourke** [comment]
Difference between list view and gallery view is to be expected too. That’s an Altis software issue if anything

**Comment by ntwb** [comment]
> Seems the takeaway then is that the tachyon container works fine but we might have an issue with the uploads URL mapping on local server which would be a separate problem to solve. Does that sound right to you?

Yes 💯

**Comment by roborourke** [comment]
Nice one @ntwb , I'll make a separate issue for the uploads mapping on local server

**Pull request merged**
