### PR TITLE
Decode special characters like @ (%40) in the path.

### PR DESCRIPTION
**Pull request by binuks**
Fixed issue: https://github.com/humanmade/tachyon/issues/32
Used decodeURIComponent instead of decodeURI to handle encoding
of characters like '@' which are not decoded by decodeURI.

### CODE REVIEW

**Comment by joehoyle** [comment]
Note to self: need to test this for backwards compat is that might cause issues.

**Comment by roborourke** [comment]
Trying this with the `master` branch and WP 4.9.6 I can't reproduce the problem however I think the change is probably desirable judging by the differences in output, `decodeURI` only partially decodes the path:

```
decodeURIComponent('/thing/stuff/image@2x.png')
-> "/thing/stuff/image@2x.png"
decodeURI('/thing/stuff/image@2x.png')
-> "/thing/stuff/image@2x.png"
decodeURIComponent('/thing/stuff/image%402x.png')
-> "/thing/stuff/image@2x.png"
decodeURI('/thing/stuff/image%402x.png')
-> "/thing/stuff/image%402x.png"
decodeURI('/thing/stuff/P%C3%B8EIi%C5%93F%402x.png')
-> "/thing/stuff/PøEIiœF%402x.png"
decodeURIComponent('/thing/stuff/P%C3%B8EIi%C5%93F%402x.png')
-> "/thing/stuff/PøEIiœF@2x.png"
```

Need to confirm if earlier versions of WP only stored encoded versions of file names in the db or actually saved the files with the encoded name format. If it's the latter I'm not sure there's much we can do about that.

**Comment by roborourke** [comment]
@joehoyle looking through some older uploads on files with encoded characters it appears there's no change in behaviour here, but with this fix both encoded and unencoded URLs will resolve correctly to the file on S3.

I reproduced the issue locally and tested the fix with Minio and `server.js`. I'm happy for this change to go in, especially seeing as how it's in `local-server.js` already.

**Comment by roborourke** [comment]
@joehoyle this has affected a few things on the demo site since we switched tachyon on there. Would be good to get this fix in. I haven't found any regressions in my testing but it'd be good to get a 2nd opinion / round of tests.

**Pull request merged**
