### PR TITLE
Add lossless compression for PNG Images

### LINKED ISSUE #76: Large PNG image error
It seems like a large image (PNG file > `2000x2000 px`) is causing an error: `{"message": "Internal server error"}`.

I’ve tried increasing the Lambda memory allocation but it hasn’t worked. Any other ideas how I might troubleshoot the issue?

### PR DESCRIPTION
**Pull request by joehoyle**
Sharp does not do a good job at creating small PNG files, especially for larger resolutions > 2000px. We add the imagemin and imagemin-pngquant plugins to compress PNG files. This is done with do quality compression / tradeoff.

Fixes #76.

### CODE REVIEW

**Comment by joehoyle** [comment]
For reference, this reduces the PNG files generated (top is before, below after).

```
┌──────────────────────────────┬───────────────┬────────────────────┬───────────────┬───────────────┬───────────────┬────────────────────┐
│ Image                        │ Original Size │ Tachyon Size       │ 100px         │ 300px         │ 700px         │ 700px webp         │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ Website.png                  │ 32.38 KB      │ 47.75 KB (147%)    │ 9.48 KB       │ 52.09 KB      │ 47.75 KB      │ 19.81 KB (41%)     │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ icons.png                    │ 94.24 KB      │ 54.39 KB (57%)     │ 6.06 KB       │ 21.2 KB       │ 51.76 KB      │ 24.23 KB (46%)     │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ humans.png                   │ 2.22 MB       │ 3.26 MB (146%)     │ 25.35 KB      │ 191.2 KB      │ 1022.58 KB    │ 138.03 KB (13%)    │
└──────────────────────────────┴───────────────┴────────────────────┴───────────────┴───────────────┴───────────────┴────────────────────┘

┌──────────────────────────────┬───────────────┬────────────────────┬───────────────┬───────────────┬───────────────┬────────────────────┐
│ Image                        │ Original Size │ Tachyon Size       │ 100px         │ 300px         │ 700px         │ 700px webp         │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ Website.png                  │ 32.38 KB      │ 33.78 KB (104%)    │ 3.34 KB       │ 13.46 KB      │ 33.78 KB      │ 19.81 KB (58%)     │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ icons.png                    │ 94.24 KB      │ 27.37 KB (29%)     │ 3.86 KB       │ 10.95 KB      │ 25.75 KB      │ 24.23 KB (94%)     │
├──────────────────────────────┼───────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼────────────────────┤
│ humans.png                   │ 2.22 MB       │ 853.21 KB (37%)    │ 8.96 KB       │ 54.78 KB      │ 273.08 KB     │ 138.03 KB (50%)    │
└──────────────────────────────┴───────────────┴────────────────────┴───────────────┴───────────────┴───────────────┴────────────────────┘
```

**Comment by roborourke** [comment]
Yeah this is exactly the approach I was looking at. Does it concern you how much slower it is to run? I’m not sure it’s avoidable really.

One other thing I realised is you might not need the entirety of imagemin. I may have misread it but on the pngquant repo the function signature is `imageminPNGQuant( opts )( Stream | Buffer )` so it might work as a direct call to the plugin.

**Comment by joehoyle** [comment]
> Yeah this is exactly the approach I was looking at. Does it concern you how much slower it is to run? I’m not sure it’s avoidable really.

I did some quick tests and didn't see this made a difference of more than 10% time, so i think it's probably ok.

>One other thing I realised is you might not need the entirety of imagemin. I may have misread it but on the pngquant repo the function signature is imageminPNGQuant( opts )( Stream | Buffer ) so it might work as a direct call to the plugin.

Interesting! I'll check in on that. Would be simpler if we could do that.

**Comment by roborourke** [comment]
@joehoyle it looks like you forgot to push a commit before merging, it’s still referencing imagemin

**Comment by joehoyle** [comment]
@roborourke yeah by bad, I hotfixed in https://github.com/humanmade/tachyon/commit/9747ce42dab8fd646677eaf2849652c23704fe83

**Pull request merged**
